FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/PhotosApi/*.csproj", "src/PhotosApi/"]
RUN dotnet restore "src/PhotosApi/PhotosApi.csproj"
COPY . .
RUN dotnet publish "src/PhotosApi/PhotosApi.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "PhotosApi.dll"]